### ISSUE TITLE
Image zoom modal is broken.

### ISSUE THREAD

**Issue by htroisi** [pixie-io/blog.px.dev#221]
The blog used to allow you to click on any image to open a modal of the image in order to zoom / pan around. Clicking on an image no longer opens a modal. 

The functionality should match that of the docs site. E.g. click the image [on this page](https://docs.px.dev/about-pixie/pixie-ebpf/).

**Comment by NickLanam** [comment]
After a quick glance out of curiosity: the error thrown in the console seems to be that `error` is undefined on [this line](https://github.com/pixie-io/blog.px.dev/blob/7739f2f262c40922af7042dbf665af98c105be76/src/components/image-zoom-modal.plugin.js#L103) in the zoom modal plugin. Didn't dig into why.
